### ISSUE TITLE
No issues (?)

### ISSUE THREAD

**Issue by danpawlik** [opendistro-for-elasticsearch/security-kibana-plugin#1]
Hi,
By removing the issues that were available in this repository, we can say that we loose solutions, workaround and any future information about bugs related to the security-kibana-plugin. I was following the issue related to the "confirmation screen" that comes even when one tenant was set: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/728 .

In that case, I would like to ask, what was the reason why community decide to remove that? Is there any alternative service that contains a "mirror" of the issues that were here?

Dan

**Comment by cliu123** [comment]
Please see: https://github.com/opensearch-project/security-dashboards-plugin/issues
