### ISSUE TITLE
opendistro-0.10 kibana not loading Authentication and Authorization

### ISSUE THREAD

**Issue by allenyin96** [opendistro-for-elasticsearch/security-kibana-plugin#115]
Authentication and Authorization is not loading in opendistro-0.10.

![image](https://user-images.githubusercontent.com/48698112/70092469-32a24700-15d3-11ea-8fd7-0a6693dd7093.png)

To repro, start a opendistro-0.10 cluster and go to Authentication and Authorization page of the security plugin.

**Comment by tclin1023** [comment]
PR for the bug fixing.
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/75

**Comment by EmPRio93** [comment]
Is there any solution ? I have the same problem right now.
