### ISSUE TITLE
Cannot destructure property `callWithInternalUser` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by fonix** [opendistro-for-elasticsearch/security-kibana-plugin#16]
log   [11:28:22.848] [info][status][plugin:index_management@6.6.2] Status changed from yellow to green - Ready
  log   [11:28:22.849] [info][status][plugin:index_lifecycle_management@6.6.2] Status changed from yellow to green - Ready
  log   [11:28:22.852] [info][status][plugin:rollup@6.6.2] Status changed from yellow to green - Ready
  log   [11:28:22.858] [info][status][plugin:remote_clusters@6.6.2] Status changed from yellow to green - Ready
  log   [11:28:22.863] [info][status][plugin:cross_cluster_replication@6.6.2] Status changed from yellow to green - Ready
  log   [11:28:22.885] [error][status][plugin:spaces@6.6.2] Status changed from yellow to red - Cannot destructure property `callWithInternalUser` of 'undefined' or 'null'.

![image](https://user-images.githubusercontent.com/1682395/56806120-4dd1fa80-682b-11e9-96a9-9b89ce0e01a2.png)

**Comment by CraightonH** [comment]
So I could get into Kibana, I added the following line to the kibana.yml file:
`xpack.spaces.enabled: false`
It would be nice to use the spaces plugin though.

**Comment by mokrinsky** [comment]
While it's intended by developers that opendistro is compatible only with OSS version of elasticsearch (so it shouldn't be used with xpack for some reason I'm not aware of), I managed to make spaces work with the small solution.

You could change following line (its line 48 or somewhere near) in security-kibana-plugin/lib/backend/opendistro_security.js:
```this._cluster = server.plugins.elasticsearch.createCluster('security', config```
and rename _'security'_ to something else, like, opendistro_security or whatever. It works for me.

**Comment by adrienyhuel** [comment]
> 
> 
> While it's intended by developers that opendistro is compatible only with OSS version of elasticsearch (so it shouldn't be used with xpack for some reason I'm not aware of), I managed to make spaces work with the small solution.
> 
> You could change following line (its line 48 or somewhere near) in security-kibana-plugin/lib/backend/opendistro_security.js:
> `this._cluster = server.plugins.elasticsearch.createCluster('security', config`
> and rename _'security'_ to something else, like, opendistro_security or whatever. It works for me.

Good job, it works with ELK 6.7.2 and X-Pack (non OSS)

**Comment by mattsdevop** [comment]
@mokrinsky @adrienyhuel thank you for posting your findings.  I've used this workaround and am experiencing an interesting UI behavior for only 1 icon. Is anyone experiencing this same thing that I opened on the opendistro forum? https://discuss.opendistrocommunity.dev/t/authentication-and-authorization-404-error-page-not-loading/1861

**Comment by mugambikimathi** [comment]
> While it's intended by developers that opendistro is compatible only with OSS version of elasticsearch (so it shouldn't be used with xpack for some reason I'm not aware of), I managed to make spaces work with the small solution.
> 
> You could change following line (its line 48 or somewhere near) in security-kibana-plugin/lib/backend/opendistro_security.js:
> `this._cluster = server.plugins.elasticsearch.createCluster('security', config`
> and rename _'security'_ to something else, like, opendistro_security or whatever. It works for me.

Works like a charm on 7.3.2

**Comment by trexx** [comment]
Whats the likelihood of this change being made to the project?

From the Opendistro FAQ:

> Can I use Open Distro for Elasticsearch plugins with the proprietary Elastic Stack?
> 
> Our plugins are tested to work with Open Distro for Elasticsearch and the OSS-only downloads from Elastic. They have not been tested with the default download from Elastic, which includes proprietary software, but we welcome the community to test and enhance individual plugins for compatibility with the Elastic Stack.

So to enhance compatibility with Elastic Stack, would this change be welcome?
