### ISSUE TITLE
Compatibility with elasticsearch, not Opendistro

### ISSUE THREAD

**Issue by ssamsonn** [opendistro-for-elasticsearch/security-kibana-plugin#183]
HI,

I want to use the kibana-security plugin with elasticsearch & kibana(7.6.1), not Opendistro.

After installing Elasticsearch & Kibana, can I install and use the kibana-security plugin?

**Comment by malcolm061990** [comment]
Hi. It works. I did.

**Comment by tianleh** [comment]
Close the issue since ssamsonn mentioned that it works.
