### ISSUE TITLE
Kibana + OpenID + Reverse Proxy => Redirect wrongly to root

### ISSUE THREAD

**Issue by hkroger** [opendistro-for-elasticsearch/security-kibana-plugin#20]
I have a setup where I have Kibana behind a reverse proxy under a sub path "/opendistro-kibana" with openID auth (keycloak).

I have configured Kibana with basePath = "/opendistro-kibana" and opendistro-security.openid.base_redirect_url = "https://somehostname.com/opendistro-kibana/".

I have configured the reverse proxy to strip path from the URL. 

When I point my browser to that location, I get redirected automatically as follows:
1) To /opendistro-kibana/auth/openid/login?nextUrl=/
2) To keycloak in some different subpath
3) Back to https://somehostname.com/opendistro-kibana/auth/openid/login?state=XXX&session_state=YYY&code=ZZZ
4) To "/" on that server which obviously is not Kibana but something completely different.

Am I doing something wrong?

**Comment by henrychancalabrio** [comment]
How did you fix this issue?

**Comment by hkroger** [comment]
I am trying to remember all the issues I had with that but unfortunately I don’t remember anymore what the problem was. I just remember that it was a bit tricky to get all configuration parameters right and the error messages were hard to figure out what went wrong. Sorry that I can’t help more.
