### ISSUE TITLE
Homepage by default

### ISSUE THREAD

**Issue by mareban** [opendistro-for-elasticsearch/security-kibana-plugin#264]
Hello,

I'm using ODFE 1.6.0.1 with security plugin, and i would like users to connect at login in a public_tenant where stand a homepage !

I can't figure out to do that, each time a user connect it's default tenant is the private one, and if i specify a tenant in the defaultRoute parameter in kibana.yml , when i connect it works but if i click on a link and go back with the browser i'm redirected to the create index page !!

Can someone help me to solve this problem, and how can i set a default tenant to a specific one ?

Thanks for your help.

**Comment by yuxitang-amzn** [comment]
Hi, 

Please check your settings in config/kibana.yml.

If it is as following
~~~
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
~~~
Try swap them to 
~~~
opendistro_security.multitenancy.tenants.preferred: ["Global", "Private"]
~~~
And then clear browser cookie and try again. It should work.
