### ISSUE TITLE
Global tenant

### ISSUE THREAD

**Issue by mareban** [opendistro-for-elasticsearch/security-kibana-plugin#266]
Hello,

In kibana.yml, i've enabled the global_tenant ! This tenant is shared by all users (from documentation), but do i have to allow read/write permissions via a Role or is it allowed automatically ?

Thanks for your help

**Comment by yuxitang-amzn** [comment]
You will still need to grant permission via a role. And for these roles the permission of global_tenant is granted implicitly:
* kibana_user
* all_access

Code ref:  

https://github.com/opendistro-for-elasticsearch/security/blob/3226dbb10f725f79edadcb53c492f6f2c3eb63ed/src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java#L1061-L1068
