### ISSUE TITLE
How can I disable access to an internal account to log in to kibana? 

### ISSUE THREAD

**Issue by arpsyapathy** [opendistro-for-elasticsearch/security-kibana-plugin#275]
Hi all!

how can I disable access to an internal account to log in to kibana?

I create internal account for beats. Map to role.
Beats send data to ES with this account.
But this account can login to Kibana.

I want to disable entry to kibana under this account.
How did it?

Thank you advanced

**Comment by yuxitang-amzn** [comment]
Try adding following line to `config/kibana.yml`:
~~~
opendistro_security.basicauth.forbidden_usernames: ["username1", "username2"]
~~~
Replace with your username and try logging in again, it should give you an 'Invalid username or Password' error.

Code reference:
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/b119256a05956556ac472b5fbde407fea69fdcf6/index.js#L47-L50  

https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/b119256a05956556ac472b5fbde407fea69fdcf6/lib/auth/types/basicauth/routes.js#L103-L106
