### ISSUE TITLE
Support for Elastic v7.8.1

### ISSUE THREAD

**Issue by manuasir** [opendistro-for-elasticsearch/security-kibana-plugin#315]
Hi team,

Just wondering when the new ODFE version is being released to support `v7.8.1`.

Regards

**Comment by zengyan-amazon** [comment]
Hi @manuasir ,

We had released ODFE 1.9.0 which supppot v7.8.0, is there anything specific in v7.8.1 you are looking at?

**Comment by manuasir** [comment]
Hello @zengyan-amazon ,

A bug was introduced in `v7.8.0` that affects the Search component, it provokes a lot of unfiltered empty fields. It was already fixed here https://github.com/elastic/elasticsearch/pull/58418 and shipped for `7.8.1`.

Thanks

**Comment by zengyan-amazon** [comment]
Hi @manuasir ,

Sorry, currently we don't have a plan of release to support `v7.8.1`. Our next planned release if `v7.9` support as of now.

Thanks
