### ISSUE TITLE
Password policy enforcement

### ISSUE THREAD

**Issue by leonwangcn** [opendistro-for-elasticsearch/security-kibana-plugin#4]
Look forward to seeing some features on password policy enforcement…for example, the password complexity, repeat, etc. enforcement…

**Comment by hardik-k-shah** [comment]
Hey @leonwangcn,

Thanks for your suggestion. 

We do already have password strength rules. You can configure it by creating complexity regex and add it into elasticsearch.yml `opendistro_security.restapi.password_validation_regex' 

For example:  Below regex only allow password with minimum 8 character long and must contain at least one upper case, one lower case, one digit and one special character. 

```
opendistro_security.restapi.password_validation_regex: "(?=.*[A-Z])(?=.*[^a-zA-Z\d])(?=.*[0-9])(?=.*[a-z]).{8,}"
```

Additionally, you can configure error message if someone try to create password which doesn't meet your configured rules. 

```
opendistro_security.restapi.restapi.password_validation_error_message: "Password must be at least 8 characters long and must contain at least one upper case, one lower case, one digit and one special character. 
 "
```

**Comment by justdaven** [comment]
If anyone decides to go with this option, I recommend a slight modification to the RegEx, as it accepts any non-alphanumeric character as a special character, including a space, I would use the following instead:

**(?=.*[A-Z])(?=.*[^a-zA-Z\d\s])(?=.*[0-9])(?=.*[a-z]).{8,}**

Adding the "\s" includes a space character to the list of exclusions for the look ahead that enforces non-alphanum chars.
