### ISSUE TITLE
Can't add Backend Roles for Internal User

### ISSUE THREAD

**Issue by t-umeno** [opendistro-for-elasticsearch/security-kibana-plugin#43]
Opendistro-for-elasticsearch version 1.0.0
Ubuntu 18.04

Can't add Backend roles for Internal User (logstash) by admin.
Please check this URL:
http://127.0.0.1:5601/app/security-configuration#/internalusers/edit/logstash?_g=()

**Comment by aetter** [comment]
Hi @t-umeno, thanks a bunch for reporting. I'm able to reproduce. Steps:

1. Open Kibana
1. Log in as admin
1. Security > Internal User Database > Add a new internal user
1. Provide username and password
1. Click Add backend role
   No text box appears

Same steps work in 0.9.0.

**Comment by t-umeno** [comment]
Hi @atter, thanks to reproduce!

2019年7月3日(水) 6:45 Andrew Etter <notifications@github.com>:

**Comment by aetter** [comment]
👍@t-umeno, we've implemented a fix and are working to roll it out soon.

**Comment by t-umeno** [comment]
Hi @aetter, thanks!

**Comment by shivdoshi** [comment]
The fix for this issue has been merged in #46 . Closing this issue, but feel free to re-open this as required.
