### ISSUE TITLE
Customerauth Error in ECK ( Elastic Cloud Kuberenetes) - “Authentication failed. Please provide a new token.”

### ISSUE THREAD

**Issue by iamvijayaragavan** [opendistro-for-elasticsearch/security-kibana-plugin#495]
I have deployed elastic cloud elasticsearch and elastic cloud kibana in my AKS system. And with little bit customization in kibana deployment to install open distro security plugin in kibana system. configured config.xml and corresponding value kibana.yml based on https://www.skedler.com/blog/kibana-single-sign-on-with-openid-connect-and-azure-active-directory/

I'm getting login window of azure and after signup getting Customerauth Error - “Authentication failed. Please provide a new token.”

My elasticcluster version 7.8.0
kibana : 7.8.0
open distro security plugin : 1.9.0

Did i miss anything here .. Do i need to install any support plugin in elasticsearch or any roles configuration.

**Comment by zengyan-amazon** [comment]
Security kibana plugin works with [OpenDistroForElasticsearch Security plugin](https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#security) for authN & authZ, so you should have both security ES and Kibana plugins installed

as you mentioned you configured `config.xml`, did you use the admin tool to update your config changes into Elasticsearch?
