### ISSUE TITLE
security plugin 2: No page reload after tenant switch 

### ISSUE THREAD

**Issue by weand** [opendistro-for-elasticsearch/security-kibana-plugin#498]
Hi,

we are testing the security platform based on new platform (based on the dev branch). 

Its good to see, that with new security plugin tenant can be switched from every place. But page should be reloaded, to present the user the tenant specific content.

Right now when switching tenant from the user menu on the top right, the page doesn't reload yet. Is that a bug?

Best regards
Andreas

**Comment by zengyan-amazon** [comment]
@tianleh can you take a look at this?

**Comment by tianleh** [comment]
Hi, weand

This is by design. We may have a backlog item to further improve the user experience for this feature.
