### ISSUE TITLE
deploy failed for opendistro_security_parent-0.7.0.1.pom

### ISSUE THREAD

**Issue by yongge666** [opendistro-for-elasticsearch/security-kibana-plugin#5]
Downloading: https://repo.maven.apache.org/maven2/com/amazon/opendistroforelasticsearch/opendistro_security_parent/0.7.0.1/opendistro_security_parent-0.7.0.1.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.amazon.opendistroforelasticsearch:opendistro_security_kibana_plugin:0.7.0.1 (/usr/local/kibana/plugins/security-kibana-plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact com.amazon.opendistroforelasticsearch:opendistro_security_parent:pom:0.7.0.1 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 27, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
/usr/share/maven/bin/mvn clean deploy -Prelease failed

**Comment by hardik-k-shah** [comment]
You can use Security 7.0.0.1 through our docker/RPM distribution version 0.7.1. 
More detail: https://opendistro.github.io/for-elasticsearch-docs/#version-history
