### ISSUE TITLE
Dark Mode not working in 1.10.1

### ISSUE THREAD

**Issue by Jakob3xD** [opendistro-for-elasticsearch/security-kibana-plugin#503]
I updated to ODFE 1.10.1 today and I noticed that the dark mode provided by Kibana does no longer work.
Dark mode is enabled an I reloaded my page but it remains white.
![grafik](https://user-images.githubusercontent.com/29206900/94806774-d379b280-03ee-11eb-86de-c56cdbccda27.png)

**Comment by NicolasDuran** [comment]
I'm having the same issue and Kibana feels realy unsuable in white mode.
Great to see there is already a pull request fixing this, hope it can be merged soon !

**Comment by zengyan-amazon** [comment]
we have fixed this as part of https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/releases/tag/v1.10.1.2 , you can download the plugin zip and install to verify

**Comment by NicolasDuran** [comment]
When will the docker https://hub.docker.com/r/amazon/opendistro-for-elasticsearch-kibana/tags be updated so I can test ?

**Comment by zengyan-amazon** [comment]
We are not going to publish a docker image for 1.10.1.2, this fix will be included in 1.11 docker image
