### ISSUE TITLE
Using 'security_tenant' in url is ignored in 1.10.1

### ISSUE THREAD

**Issue by jjmerchante** [opendistro-for-elasticsearch/security-kibana-plugin#505]
I have updated from OpenDistro 1.8 to 1.10.1. 

In the newer version when I try to access to Kibana using the query string `security_tenant=xxx` it is ignored, while in 1.8 it works.

The query is  `/app/dashboards?security_tenant=tenant_workspace_1` as documented at https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/

**Comment by zengyan-amazon** [comment]
@jjmerchante  https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/511 should have fixed this. we have released a patch version of security kibana plugin [v1.10.1.2](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/releases/tag/v1.10.1.2) which includes this fix. Our future ODFE versions will also include this fix.

**Comment by zengyan-amazon** [comment]
closing, feel free to reopen if there is still any problem
