### ISSUE TITLE
Global tenant is grayed out in kibana 1.10.1

### ISSUE THREAD

**Issue by sushovan23** [opendistro-for-elasticsearch/security-kibana-plugin#509]
After upgrading to kibana 1.10.1. Global tenant is grayed out for non admin user. Once I give myself admin privileges it works but global tenant should be available to everyone regardless of admin or not. Please fix this as it is essential when sharing visualizations and dashboards. 

![image](https://user-images.githubusercontent.com/14843483/95138500-5c1e8880-0738-11eb-9e59-4225a169b616.png)

**Comment by zengyan-amazon** [comment]
@yuxitang-amzn can you help to take a look?

**Comment by yuxitang-amzn** [comment]
Hi there, 

We may need more information could you paste your authinfo here?

Steps to do:
1. Login
2. Navigate to http://localhost:5601/api/v1/auth/authinfo (replace `http://localhost:5601` with your kibana server address)
You should be able to see a json like this.

~~~json
{
  "user": "User [name=admin, backend_roles=[abc, bcs], requestedTenant=]",
  "user_name": "admin",
  "user_requested_tenant": "",
  "remote_address": "72.21.198.64:9200",
  "backend_roles": [
    "abc",
    "bcs"
  ],
  "custom_attribute_names": [
    
  ],
  "roles": [
    "all_access",
    "kibana_user_copy",
    "security_manager"
  ],
  "tenants": {
    "DOIDSJ": true,
    "admin": true,
    "abc": true,
    "global_tenant": true
  },
  "principal": null,
  "peer_certificates": "0",
  "sso_logout_url": null
}
~~~

**Comment by sushovan23** [comment]
```
{
    "user": "User [name=<userprincipalname>, backend_roles=[Admin], requestedTenant=__user__]",
    "user_name": "<userprincipalname>",
    "user_requested_tenant": "__user__",
    "remote_address": "127.0.0.1:49307",
    "backend_roles": [
        "Admin"
    ],
    "custom_attribute_names": [
        "attr.jwt.iss",
        "attr.jwt.preferred_username",
        "attr.jwt.oid",
        "attr.jwt.rh",
        "attr.jwt.uti",
        "attr.jwt.roles",
        "attr.jwt.aud",
        "attr.jwt.nbf",
        "attr.jwt.tid",
        "attr.jwt.sub",
        "attr.jwt.name",
        "attr.jwt.ver",
        "attr.jwt.exp",
        "attr.jwt.iat",
        "attr.jwt.email"
    ],
    "roles": [
        "own_index"
    ],
    "tenants": {
        "<userprincipalname>": true
    },
    "principal": null,
    "peer_certificates": "0",
    "sso_logout_url": null
}

```

@yuxitang-amzn

**Comment by zengyan-amazon** [comment]
@sushovan23 it looks this user has `Admin` as its backend role, but that backend role is not mapped to any security role in your ODFE instance. 

Can you try to map backend role `Admin` to `kibana_user` role, and re-login using this user?

You can do it by
1. navigating to `kibana_user` role
2. go to `Mapped users` tab
3. click `Manage mapping`
4. add `Admin` in External identities section
5. save the change by clicking `Map` button

**Comment by sushovan23** [comment]
@zengyan-amazon Is this also something new with 1.10.1? Because with 1.8 and 1.6 it is configured in same way and user with `all_access` mapping or basically any user who could login to kibana  was able to switch to global tenant. So I expected same behavior to continue

**Comment by sushovan23** [comment]
I have verified again with 1.8.0. When I do not have `all_access` and only have `own_index` I can still switch to global tenant. So its a breaking change in 1.10.1. Is that by design or a bug which will be fixed? Because I would need to patch our install and upgrade processes to include the above steps via apis(if available) because we would like to make it out of box rather than having admin change it

**Comment by zengyan-amazon** [comment]
I am a bit confused by your setup. Technically, if a user has only `[own_index]`, this user is not able to query any data on ES, thus being able to access dashboard/visualization is not useful at all.

Or you mean, on your 1.8.0 setup, even if a user has only `[own_index]` while doesn't have any other permission, they can still query ES data and see dashboards?

**Comment by yuxitang-amzn** [comment]
Hi,

For global tenant, this is by design. The only 2 roles that implicitly inherit global tenant permission are `kibana_user` and `all_access`. Code ref:
https://github.com/opendistro-for-elasticsearch/security/blob/3226dbb10f725f79edadcb53c492f6f2c3eb63ed/src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java#L1061-L1068

Not 100% sure for 1.8.0. Maybe you granted all_access initially and removed later? In this case if you clear cookie and caches it should be gone.

**Comment by sushovan23** [comment]
you are right. it was my browser which confused me with the expected behavior. 
So non admins login. they are private. If admins want them to see something they then map it to a role. Thanks for clarifying. 

I will close this issue. While I have you all here can anyone tell me how to leverage Azure AD groups while mapping roles to users? We want to map Azure AD groups in kibana role mapping somehow. Any pointers on how to do that would benefit us

**Comment by zengyan-amazon** [comment]
A would assume `Admin` is one of your Azure AD group, and you are using it as the backend_role of ODFE security role here.

you can refer to ODFE security plugin roles_mapping API ( https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#role-mappings ) to create role mappings to map your Azure AD group to the security role you want to assign to the AD group.

Let us know if you have any questions.

**Comment by sushovan23** [comment]
For questions related to Azure AD group do I open more questions here or is there another way to engage the core team? Thanks again for helping us a lot with login issue

**Comment by zengyan-amazon** [comment]
the roles mapping is managed by the ODFE Elasticsearch Security plugin, while Kibana is just a passthrough layer for visualization. if you want to automate the roles mapping process via APIs, you may want to open questions in ODFE Elasticsearch Security plugin repo ( https://github.com/opendistro-for-elasticsearch/security/issues ) and the ES security plugin guys should help. I understand this is annoying to go here and there for help on those issues :( Sorry for the inconvenience.

**Comment by sushovan23** [comment]
Thanks I will reach out there when I take the Azure AD groups mapping user story. This helps a lot. I’ll wait for the new release or patch release with the kibana login fix.

**Comment by lukasmrtvy** [comment]
@sushovan23 are You using AAD groups instead of roles ? We are not using AAD P1 nor P2, where are custom roles supported. So wondering if AAD groups would work.
