### ISSUE TITLE
Can't map external users to roles in new UI

### ISSUE THREAD

**Issue by shawnz** [opendistro-for-elasticsearch/security-kibana-plugin#513]
With the new security UI, it's not possible to map external users to roles anymore.

I have some external users already mapped to roles from the previous version, and now when I view the new "mapped users" page, those users show as internal users (even though they are external). I can delete them but I can't add any additional external users from the UI.

**Comment by zengyan-amazon** [comment]
@yuxitang-amzn can you take a look at this issue?

**Comment by yuxitang-amzn** [comment]
Hi shawnz,

There is a manage mapping button that should allows you to add.
![image](https://user-images.githubusercontent.com/63078162/95263481-b2480600-07e2-11eb-9bbe-9c006fb5c638.png)

**Comment by shawnz** [comment]
That page only allows you to add internal usernames, not external usernames from the backend authentication system

**Comment by zengyan-amazon** [comment]
@shawnz what do you mean by "external username" here?

In OpenDistroForElasticsearch security, a role can only be mapped to `internal users` or `backend roles` (on the new UI, backend role is shown as `external identity`).
* an `internal user` is an user created via security plugin's [internal user API](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#create-user) , and completely managed by the security plugin
* a `backend role` (or `external entity`) is an attribute that exists in the external IDP, when you use auth types like OpenIDConnect or SAML or LDAP. 

It will be very helpful if you can elaborate your setup, so that we can understand this issue better

**Comment by shawnz** [comment]
For example, I have a user provided by an external SAML IdP with username `szivonts`. This is the user I use to log in to Kibana.

In previous versions of the security Kibana plugin, I could add the username `szivonts` to the role mapping for the all_access role, despite it not being an internal user, and I would receive that role. But now, it is not possible to add external usernames to the mapping, only internal usernames.

However, I can still add such users to mappings by using securityadmin.sh to modify the roles_mapping.yml file, and it works fine, just as in the previous version. The problem is simply that the UI only allows internal usernames to be entered, not external usernames.

**Comment by zengyan-amazon** [comment]
thanks @shawnz !  @yuxitang-amzn are you aware of this ?

**Comment by zengyan-amazon** [comment]
@dinusX @hardik-k-shah is this officially supported to allow roles to map to usernames from external IDP ?

**Comment by shawnz** [comment]
If this change is intended and the new behaviour is to be kept, we won't be able to use our organization's IdP with Kibana any more which will be very frustrating. Unfortunately our organization's IdP is administered by a different department and they manage around 100k users, so they will not want to create separate roles in the IdP for the few dozen users which our department needs to give access to each index in ES. Please consider allowing arbitrary usernames to be entered again like the previous security UI did.

**Comment by tmashos** [comment]
This is something that definitely worked prior to our 1.10.1 upgrade. It also still works for users that were setup prior to 1.10.1.

On a hunch, I tried role mapping external users by username via the [API](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#create-role-mapping) and that also seems to work. So it just seems this is a regression in the Kibana plugin.

**Comment by yuxitang-amzn** [comment]
We pushed a fix for it. It will be included in next release. You may also try build from source if you don't want to wait. I'm going to closing this issue. Feel free to re-open if you have further concern on this issue.

**Comment by shawnz** [comment]
Thank you so much for the fast response.
