### ISSUE TITLE
After upgrading to 1.10.1 from 1.8 kibana login is not working

### ISSUE THREAD

**Issue by sushovan23** [opendistro-for-elasticsearch/security-kibana-plugin#514]
**Describe the bug**
performed upgrade to 1.10.1 from 1.8. 
All elasticsearch nodes are up and cluster is green. 
Before upgrade cluster was configured with openid/sso. we were able to login correctly.
After upgrade when I try to login to kibana its giving following error:

{"statusCode":400,"error":"Bad Request","message":"[request query.session_state]: definition for this key is missing"}

**To Reproduce**
1. upgrade to 1.10.1 from 1.8  (elasticsearch should be configured
2. upgrade opendistro kibana
3. try to login
{"statusCode":400,"error":"Bad Request","message":"[request query.session_state]: definition for this key is missing"}
**Expected behavior**
Able to login to kibana using sso.

**Configuration (please complete the following information):**
 - ODFE/Kibana version [1.10.1]
 - Distribution [RPM]
 - Host Machine [Centos7]

Did something change in the way security plugin is configured? Because I have it working correctly in 1.6 and 1.8.

**Comment by zengyan-amazon** [comment]
@arnitolog your configuration looks correct, I have tried to reproduced using similar config on my side, and it works ok.

Usually infinite redirection loop is caused by cookie not properly passed between server and browser. Can you check the requests in your browser developer tool and see if the `set-cookie` headers returned by kibana server are honored by the browser?

**Comment by zengyan-amazon** [comment]
@plnordquist we had a fix to allow the `session_state` parameter https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/510 , we plan to release a patch version of security kibana plugin soon in next few days, then you should be able to turn the session management option back on

**Comment by zengyan-amazon** [comment]
> Is there any private version of v1.10.1.2 kibana image to test ? Thanks

@lukasmrtvy  you can download a snapshot version of v1.10.1.2 security kibana plugin at https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-security/opendistro_security_kibana_plugin-1.10.1.2.zip

**Comment by lukasmrtvy** [comment]
@zengyan-amazon I am looking for a docker image ( I am using helm chart, its not so easy to mount & install plugin at deploy time .. )

I modified official image https://github.com/lukasmrtvy/opendistro-for-elasticsearch-kibana-fix/blob/main/Dockerfile#L3

Helm args:
`--set kibana.image=lukasmrtvy/opendistro-for-elasticsearch-kibana-fix` & `--set kibana.imageTag=latest`

Problem is that hub.docker.com has problems https://status.docker.com/pages/history/533c6539221ae15e3f000031 and I can not build image .. 

Will try asap..

**Comment by arnitolog** [comment]
@zengyan-amazon I checked `set-cookie` header and found an error:
Set-Cookie header is ignored in response from url: https://logs-test.us.dev.kube.company.com/auth/openid/login?state=abKJ_B2F8UGxIw7HWbhWIp&code=a950100f-19d1-4bb6-8b50-0557362be14b.1e86c530-392c-4bd2-81fa-ca31a25db5f2.208d33ca-1735-423c-8075-8860fa0a8c34. Cookie length should be less than or equal to 4096 characters.
Are there any changed introduced in ODFE 1.10.1 how cookies are formed. Exactly the same config is working fine with ODFE 1.9.0

**Comment by zengyan-amazon** [comment]
@arnitolog yes, we do have changes regarding cookie in 1.10.1. 

In 1.10.1 openID connect auth, we save both [id_token and refresh_token](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/652746e716c340bcdd3cb2f31a2e212c40f0f361/server/auth/types/openid/routes.ts#L146-L150) in cookie, to support [token refresh](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/652746e716c340bcdd3cb2f31a2e212c40f0f361/server/auth/types/openid/openid_auth.ts#L144), while in 1.9.0 and older versions, we only save [`id_token`](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/c2136d70cc19196a8b1fb14f9eb12ef1c8ad70ec/lib/auth/types/openid/routes.js#L130-L134) in cookie.

this might be the reason of increased cookie size. So if you have a lot of attributes from your IDP, then your `id_token` might be already pretty big and adding the refresh token might make it exceeded the 4096 byte limit.

Can you create a new issue in [Kibana security plugin repo](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues) ? We can track this cookie size problem separately using that issue.

**Comment by arnitolog** [comment]
thank you @zengyan-amazon. I've created https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/516

**Comment by zengyan-amazon** [comment]
we have released [`v1.10.1.2`](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/releases/tag/v1.10.1.2) of Kibana security plugin, which fixed a few issues including this OpenID parameter problem. You can download the plugin zip bundle from the release and install it using `kibana-plugin install` command. We are not going to release a new ODFE bundle or image for this fix.

**Comment by sushovan23** [comment]
So this would be special handling for 1.10.1 and in later version it would be included in rpm? 

Also what are the steps to install it? Copy over zip , unzip it and install using kibana-plugin install command? We have our provisioning/upgrade via ansible playbooks so asking as it would require changing our playbooks to handle this version.

**Comment by zengyan-amazon** [comment]
@sushovan23 yes, this is a patch release of Kibana security plugin for 1.10.1. We will definitely include the fixes in future ODFE versions in their rpm/docker image etc. According to [ODFE roadmap](https://github.com/orgs/opendistro-for-elasticsearch/projects/3), the next ODFE version should be 1.11.0.

you can use the [`kibana-plugin`](https://www.elastic.co/guide/en/kibana/current/install-plugin.html) command to install the plugin. e.g. 
```
<kibana_dir>/bin/kibana-plugin install https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/releases/download/v1.10.1.2/opendistro_security_kibana_plugin-1.10.1.2.zip
```
if you have the 1.10.1.1 version installed, you may want to uninstall it first by executing
```
<kibana_dir>/bin/kibana-plugin remove opendistro_security
```

**Comment by darkdragn** [comment]
@zengyan-amazon AWESOME! It worked perfectly. The biggest thing was that I'm using the helm chart and you guys don't have a docker image on it right now, so I just rebuild the 1.10.1 from your repo. if anyone wants to use the fixed kibana image before they get one up, or if you want to retag mine and push it:  darkdragn/opendistro-for-elasticsearch-kibana:1.10.1.2

Thanks again @zengyan-amazon  , you're awesome, man.

**Comment by zengyan-amazon** [comment]
@darkdragn Thank you!  As you can see from `https://github.com/orgs/opendistro-for-elasticsearch/projects/3` we are currently working on 1.11 release which is still on Elasticsearch 7.9, which several new features or feature enhancements. This fix will definitely include in the 1.11 release with the image.

**Comment by sushant-pradhan** [comment]
> @zengyan-amazon AWESOME! It worked perfectly. The biggest thing was that I'm using the helm chart and you guys don't have a docker image on it right now, so I just rebuild the 1.10.1 from your repo. if anyone wants to use the fixed kibana image before they get one up, or if you want to retag mine and push it: darkdragn/opendistro-for-elasticsearch-kibana:1.10.1.2
> 
> Thanks again @zengyan-amazon , you're awesome, man.

Hey @darkdragn  I have the same setup as yours and faced similar error as in this thread. I took the image published by you: darkdragn/opendistro-for-elasticsearch-kibana:1.10.1.2 and changed kibana.yml to `opendistro_security.cookie.secure: false`. However, I am still getting error with Kibana login. Can you share your configurations. I guess I am missing some additional change

**Comment by darkdragn** [comment]
> > @zengyan-amazon AWESOME! It worked perfectly. The biggest thing was that I'm using the helm chart and you guys don't have a docker image on it right now, so I just rebuild the 1.10.1 from your repo. if anyone wants to use the fixed kibana image before they get one up, or if you want to retag mine and push it: darkdragn/opendistro-for-elasticsearch-kibana:1.10.1.2
> > Thanks again @zengyan-amazon , you're awesome, man.
> 
> Hey @darkdragn I have the same setup as yours and faced similar error as in this thread. I took the image published by you: darkdragn/opendistro-for-elasticsearch-kibana:1.10.1.2 and changed kibana.yml to `opendistro_security.cookie.secure: false`. However, I am still getting error with Kibana login. Can you share your configurations. I guess I am missing some additional change

Here you go, man. I removed my keycloak stuff and my domain names, but other than that everything is the same. Also, I'm using a manual secret for config.yaml to be the security config. I found that the "easier" method in there does a directory mount which drops everything and I didn't want to recreate all of the base configs in my values.yaml. It also has some of the keys(Filenames) wrong in the base values.yaml that gave me a migraine, so using the single secret way was easier for me.

https://gist.github.com/darkdragn/e19982150306ebd4368c6fdb890a7303

**Comment by sushant-pradhan** [comment]
Thank you @darkdragn I am now getting a different error: `redirected you too many times. (ERR_TOO_MANY_REDIRECTS)`. I suspect similar issue to the one faced by @arnitolog . @zengyan-amazon  is it because #516 is still open and there is no patch yet? Or may be its not part of `arkdragn/opendistro-for-elasticsearch-kibana:1.10.1.2`?

**Comment by sushovan23** [comment]
@zengyan-amazon  Did this make it to release 1.11.0 which was released yesterday?

**Comment by sushant-pradhan** [comment]
> @zengyan-amazon Did this make it to release 1.11.0 which was released yesterday?

It doesn't look like. I still get TOO_MANY_ATTEMPTS error after the upgrade. @zengyan-amazon  can confirm the latest on this though. Kind of blocked and doesn't seem to have a working solution/workaround

**Comment by zengyan-amazon** [comment]
@sushant-pradhan if you get `ERR_TOO_MANY_REDIRECTS` , it looks more like the same issue as #516 , can you check the cookie size and your JWT token size?

We don't have a patch for #516 yet, our team is still discussing how to solve the root cause of this issue.

**Comment by sushant-pradhan** [comment]
@zengyan-amazon  yes after the upgrade, the cookie shows invalid (i assume because of it exceeds allowed length). I can't downgrade to a lower version too. Kind of a limbo state.

**Comment by ch3lo** [comment]
> @zengyan-amazon yes after the upgrade, the cookie shows invalid (i assume because of it exceeds allowed length). I can't downgrade to a lower version too. Kind of a limbo state.

I had the same problem using opendistro with Keycloak SSO. As a workaround I removed some flields mapped to JWT (claim). For example, remove displayName, user_prefered, phone, etc. I think you don't need those fields to assing roles and permissions.

Regards
