### ISSUE TITLE
Switch tenant dialog appears at every login - althought there's only one tenant to choose

### ISSUE THREAD

**Issue by alexbde** [opendistro-for-elasticsearch/security-kibana-plugin#519]
I just upgraded to latest version 1.10.1 and noticed dialog to switch tenant after login. Usually, I'd say this a great idea, but the issue in my case is there's is only one tenant I can choose from. Meaning extra dialog becomes senseless and annoying as it appears on every login.

Why is there only one tenant in my case? We are using shared users for every project instead of personal users. I know it isn't the best option security-wise but it's a senseful intermediate step in our migration scenario (coming from everybody is using the admin account in legacy system). That's why I disabled the private tenant. Furthermore, it makes no sense to share items between different tenants in our case, so global tenant is also disabled.

Result is, every user is redirect to `<kibana>/app/select_tenant?nextUrl=%2F` after login and forced to choose between following options, which doesn't make much sense and is more confusing than helpful:

![kibana-dialog](https://user-images.githubusercontent.com/17784818/95432837-754d5200-094f-11eb-99ed-b1c62f9123d1.png)

So, I'd propose one of the following solutions:

- show dialog only once for every user (they can invoke it on demand anyway)
- skip dialog if there's only one tenant to choose
- add configuration option to set default tenant per user (which will skip dialog of course)

What do you think?

**Comment by zengyan-amazon** [comment]
@alexbde thanks for reporting this case, we will have a discussion about what kind of experience we want to provide for such case.

And btw, may I know your thoughts? e.g. default to the only tenant so that you can simply confirm and move forward, or show a toast notification to let you know you are on that tenant, or simply skip this tenant selection dialog?

**Comment by alexbde** [comment]
Sure, thank you for quick response.

I'd prefer the following (in descending order):

- skip dialog on login when there's only one tenant available for a user (because this happens always on purpose of the administrator)
- add configuration option to skip dialog at login (e. g. `opendistro_security.multitenancy.skip_dialog_at_login` in `kibana.yml`)
- add configuration option to set default tenant for user (e. g. `<user>.default_tenant` in `internal_users.yml`). This might be a good idea anyhow. Right now simply the first one is chosen, I guess?
- show dialog only once for every user (they can invoke it on demand anyway)

Nota bene: as I really like the tenant feature of Open Distro and think it's a core value, you could even think of placing tenant output and chooser more visible. For example next to the new user icon on the top right. There is some space now because user name is not displayed anymore. This way there's no need for dialog or toast notification as you're always aware of chosen tenant and can switch it with ease.

By the way: I just noticed I don't get the tenant selection dialog in my admin account in which all four tenants are available. Is there already a way to disable this dialog or why isn't it shown for admin?

**Comment by zengyan-amazon** [comment]
@alexbde sorry for the delay, we get feedback from our UX, and the plan is to skip the tenant selection if there is only one tenant available for the user. Let us know if you have any question or concern.

**Comment by zengyan-amazon** [comment]
using #615 to track this
