### ISSUE TITLE
When multi-tenancy is disabled selecting Security->Tenants brings empty page

### ISSUE THREAD

**Issue by vrozov** [opendistro-for-elasticsearch/security-kibana-plugin#521]
Starting with 1.10.1.x selecting "Security"->"Tenants" leads to an empty page when multi-tenancy is disabled. Selecting "Security" does not bring back "Security" home page.

**Comment by zengyan-amazon** [comment]
will use  https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/520 to track UI issue when multi-tenancy is disabled

**Comment by vrozov** [comment]
Note that they are two separate UI issues even though both are related to multi-tenancy being disabled.

**Comment by tianleh** [comment]
Merged the change to add an instruction page for tenant list in case disabled multitenancy.
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/546

(Note the other tenant switch on profile button is still pending research)
