### ISSUE TITLE
Switching tenants doesn't invoke page reload (since 1.10.1)

### ISSUE THREAD

**Issue by alexbde** [opendistro-for-elasticsearch/security-kibana-plugin#523]
When I used the new switch tenants feature from dropdown box on top right, I'd expect it to reload the page. Otherwise it will display the data from the tenant selected before.

Steps to reproduce:

- Login
- Click on user icon on top right
- Click on `switch tenants`
- Choose tenant
- Confirm

=> Nothing happens. Even the user icon dialog is still visible:

![image](https://user-images.githubusercontent.com/17784818/95552532-1e0db700-0a0d-11eb-9331-83279bb3c60f.png)

**Comment by Mudboyzh** [comment]
I have same problem after upgrading(1.9.0 -> 1.10.1) and can not switch tenants even reload manually from dropdown box or tenants page.
There's no error in console or network request.
It's same after upgrading to 1.10.1.2.

**Comment by zengyan-amazon** [comment]
@yuxitang-amzn can you take a look at this

**Comment by l14** [comment]
The tenant switch is working when using basic auth, but not with the proxy auth.
When using proxy auth the call _api/v1/configuration/account_ always returns with user_requested_tenant: "__user__"
Maybe a issue on the backend ?

**Comment by yuxitang-amzn** [comment]
@Mudboyzh @l14 Could you check if you have added 'securitytenant' to `elasticsearch.requestHeadersWhitelist` as per: https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/

**Comment by Mudboyzh** [comment]
Hi @yuxitang-amzn  Thanks! It works for me. Now I can switch tenant with manually reloading after adding 'securitytenant'  to `elasticsearch.requestHeadersWhitelist` .

**Comment by l14** [comment]
> @Mudboyzh @l14 Could you check if you have added 'securitytenant' to `elasticsearch.requestHeadersWhitelist` as per: https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/

Yes, I have:
elasticsearch.requestHeadersWhitelist: [ "Authorization", "securitytenant", "x-forwarded-for", "x-proxy-user", "x-proxy-roles","x-proxy-ext-perms" ]

**Comment by zengyan-amazon** [comment]
@l14 yes, I looked at the code and I can confirm the tenant in cookie is ignored in case of proxy auth, will create a fix soon.

**Comment by yuxitang-amzn** [comment]
@l14 We have pushed a PR #548 to fix it. You can download the release [v1.11](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/releases/tag/v1.11.0.0) or build from source yourself.

I'm closing this issue, feel free to re-open if you have further concern.
