### ISSUE TITLE
Warning after switching tenants (since 1.10.1)

### ISSUE THREAD

**Issue by alexbde** [opendistro-for-elasticsearch/security-kibana-plugin#524]
After switching tenants (and reloading page) following toast notification appears: `"undefined" is not a configured index pattern ID. Showing the default index pattern: "example-*" (example-*)`.

![image](https://user-images.githubusercontent.com/17784818/95553818-7ba30300-0a0f-11eb-9a9e-cc6e5a860829.png)

Steps to reproduce:

- steps from #523 
- reload page manually
- toast notification appears

Is this behaviour intended? Never noticed it before ODFE 1.10.1.

**Comment by bandinib-amzn** [comment]
Hi @alexbde 

I am able to reproduce the error. I am just observing this warning toast on Discover page. Did you see the same kind of warning on other pages like dashboard, visualization ?

**Comment by alexbde** [comment]
Hi @bandinib-amzn,

I just double-checked and warning is only showing on Discover page. Thank you for looking at it!

**Comment by alexbde** [comment]
@zengyan-amazon @bandinib-amzn  Does closing issue mean it is solved? In which version was it resolved?
