### ISSUE TITLE
Unable to create a new action group with new action

### ISSUE THREAD

**Issue by skkosuri-amzn** [opendistro-for-elasticsearch/security-kibana-plugin#530]
We added new actions to alerting plugin. Unable to create a new action group with the new action.
Followed:
`Security -> Permissions -> Create action group -> Create from blank`. Gave a name and added new action, Saved. When I reopen the saved action group, action/permission is not present.

![image](https://user-images.githubusercontent.com/59816283/96035546-01f88400-0e18-11eb-9a1e-8035bfd9bf66.png)

**Comment by zengyan-amazon** [comment]
@yuxitang-amzn `indices:admin/resolve/index` should be added to https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/main/public/apps/configuration/constants.tsx

**Comment by yuxitang-amzn** [comment]
Hi, we pushed a fix to this issue. It will be included in next release. You can also build from source if don't want to wait. 

I'm closing this issue. Feel free to re-open if you have further concern.

**Comment by zengyan-amazon** [comment]
@yuxitang-amzn as part of https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/529 , we may want to add `indices:admin/resolve/index` to our permission list
