### ISSUE TITLE
Assets missing from release v1.10.1.2

### ISSUE THREAD

**Issue by andykellr** [opendistro-for-elasticsearch/security-kibana-plugin#540]
I am running Kibana from source. When I copy the `opendistro_security` plugin into my plugins folder, Kibana complains that the following files are missing:

```
./public/assets/get_started.svg
./public/assets/open_distro_for_elasticsearch_logo_h.svg
./public/apps/configuration/_index.scss
./public/apps/configuration/panels/audit-logging/_index.scss
./public/apps/configuration/panels/permission-tree/_index.scss
./public/apps/configuration/panels/role-edit/_index.scss
./public/apps/configuration/panels/role-edit/_index.scss
./public/apps/login/_index.scss
./public/index.scss
```

These files exist in the source repo but are not included in `opendistroforelasticsearch-kibana-1.10.1.tar.gz` or `opendistro_security_kibana_plugin-1.10.1.2.zip` from the releases of this repo.

I confirmed that assets like these were included in `opendistroforelasticsearch-kibana-1.9.0.tar.gz`

**Comment by zengyan-amazon** [comment]
@andykellr the zip bundle includes the optimized JS file for browser side plugin, and the assets like the images and CSS are transpiled into the optimized JS. Hope this answers your questions.
