### ISSUE TITLE
security_tenant not end-2-end handled

### ISSUE THREAD

**Issue by rsmeyers** [opendistro-for-elasticsearch/security-kibana-plugin#552]
I'm running 1.10.1 with the fix for https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/511
Although I can see security_tenant is now somehow handled, I still see 2 issues:
a) I'm being forced on a new login to select a tenant, although I'm explicitly putting it in my URL
b) As per the login cycle, I'm loosing my redirect and end up in the normal 'dashboard' view when using the following URL for example:

https://MyHost/kibana/app/dashboards?security_tenant=my_tenant#/view/58ea38b0-1392-11eb-a0f9-c9113bcbe262?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:MyData,viewMode:view)

**Comment by zengyan-amazon** [comment]
@rsmeyers we created #586 to address `a)` and `b)` should have been addressed with #577 if you are using basic authentication.

**Comment by rsmeyers** [comment]
@zengyan-amazon tx for fixing this, in which release do we expect this to be included ? I saw we just released 1.11.0-1 as RPM, any chance both fixes will be included soon in a released rpm ?

**Comment by yuxitang-amzn** [comment]
Hi @rsmeyers,

We don't have a plan to release an RPM for the fix. You may wait for 1.12 (targeting kibana 7.10) or try building from source.

I'm going to close the issue. Feel free to re-open if you have further concern.

**Comment by rsmeyers** [comment]
I can confirm after upgrading to 1.12.0 this is now working
