### ISSUE TITLE
"Application Not Found" when creating a read-only user as per docs 

### ISSUE THREAD

**Issue by stockholmux** [opendistro-for-elasticsearch/security-kibana-plugin#562]
When following the [sequence for creating a read-only role in the docs (heading: "Set up a read-only user in Kibana")](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/#sample-roles) and then trying to login with the created user, the login sequence hangs at `http://localhost:5601/app/select_tenant?nextUrl=%2Fapp%2Fhome` with a `Application Not Found` message. 

![Screen Shot 2020-10-26 at 10 47 41 AM](https://user-images.githubusercontent.com/1152927/97202050-bda2a780-1778-11eb-9af5-5820ba656925.png)

Seems to be related to read-only users. You can continue by manually changing the URL to `/app/home`.

**Comment by tianleh** [comment]
If the user has no admin permission (API permission), then they won't have access to security related pages. 

Can you try http://localhost:5601/app/ ?

**Comment by FahadAlMutairi5** [comment]
Dears 
i have this issue with the user have kibana_read_only permission and i try with `/app/` and get this error 
![image](https://user-images.githubusercontent.com/47291969/97300004-e43f0c00-1866-11eb-9746-da16e430797b.png)
can we change the redirect url nested of `app/select_tenant` to be `app/home`  because the `app/home` url it's work fine

**Comment by stockholmux** [comment]
@tianleh This isn't navigating to a security related page - this is immediately following login. Effectively a user can't login unless they know to go to `http://localhost:5601/app/home#/`.

Seems to be related to read-only permissions.

**Comment by FahadAlMutairi5** [comment]
Please any support for this issue 
It’s affected our production environment

**Comment by yuxitang-amzn** [comment]
@stockholmux @FahadAlMutairi5 
We are raising a PR to fix this issue. Will let you guys know when it is merged.

**Comment by yuxitang-amzn** [comment]
@stockholmux @FahadAlMutairi5 
We've merge the PR. We'll include the fix in next release. Alternatively you can also build from source. 

I'm closing the issue now, feel free to re-open if you have further concern.
