### ISSUE TITLE
Performing tenant migrations in parallel leads to timeouts

### ISSUE THREAD

**Issue by andykellr** [opendistro-for-elasticsearch/security-kibana-plugin#580]
We upgraded a cluster with around 100 tenants and the first 30 or so succeeded but the rest timed out.

Because the first step of migration--creating the index--succeeded, restarting Kibana resulted in errors due to these migrations being in process.

We deleted the new indices for the 70 or so failed migrations to restart the migration process and got through another 30 with the remaining 40 timing out. We repeated this process until we were able to migrate all tenants.

This was disruptive and time consuming, but we got through it.

I will post a PR shortly, but I think `server/multitenancy/tenant_index.ts:97` should be changed to a `for...of` loop to run migrations one at a time. The migration process is too fragile to attempt them all at once.

```js
  Object.keys(tenentInfo).forEach(async (indexName, i, array) => {
```

should change to

```js
  for (const indexName of Object.keys(tenentInfo)) {
```

**Comment by zengyan-amazon** [comment]
@andykellr how did you confirm the index migration failed due to timeout? Kibana index migrator has a known issue of racing condition when multiple Kibana instance trying to migrate the same index, like issue described at https://discuss.elastic.co/t/kibana-pod-doesnt-come-up-log-says-another-kibana-instance-appears-to-be-migrating-the-index-waiting-for-that-migration-to-complete/251850/2

**Comment by andykellr** [comment]
Because of how fragile the process can be, we only run a single pod when upgrading and performing migrations. This was not a race condition.

I do not have the logs handy right now, but there was a clear 30s timeout indicated.

**Comment by zengyan-amazon** [comment]
@andykellr I see, thanks for the explanation. Thanks for contributing to the project! We will look at your PR once it is out.

**Comment by andykellr** [comment]
Here's an example of one of the stacks:

```
"UnhandledPromiseRejectionWarning: Error: Request Timeout after 30000ms
    at /usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:397:9
    at Timeout.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:429:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    at emitWarning (internal/process/promises.js:97:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
    at process._tickCallback (internal/process/next_tick.js:69:34)"
```

And a screenshot so you can see that this happens quite a bit:

<img width="1726" alt="Screen Shot 2020-10-29 at 6 13 57 PM" src="https://user-images.githubusercontent.com/2660251/97638418-e04fed00-1a12-11eb-9100-2bcb83f732d1.png">

Also, You will see, for example, `Finished in 28942ms.` showing that some are able to finish just under 30s, but because there are so many happening at once, they all stack up and eventually timeout.

**Comment by zengyan-amazon** [comment]
@andykellr The PR looks good, I have merged it in. Thank you!
