### ISSUE TITLE
Short Url not working since 1.11.0

### ISSUE THREAD

**Issue by AlexShuraits** [opendistro-for-elasticsearch/security-kibana-plugin#591]
The "short URL" functionality was broken since I have upgraded to 1.11.0.

When clicking Copy Link the link is copied but not opened afterwards.
![image](https://user-images.githubusercontent.com/7362416/97985944-a485a080-1de1-11eb-9ebc-b37f0137fc58.png)

`{"statusCode":404,"error":"Not Found","message":"Saved object [url/c93cb7bba8f79a16c2fd69ab2520342d] not found"}`

The tenant parameter is not added to the link as it was before.

**Comment by tmashos** [comment]
I'm having this same issue on 1.10.1 and it does seem to be a bug rather than a permissions issue as it doesn't even work with an all access user.

**Comment by AlexShuraits** [comment]
I have bumped the OD 2 versions from 1.9.0 to 1.11.0, so it looks like the issue exists since 1.10.1

**Comment by weand** [comment]
we are  on 1.10.1 and face some similar error, when using the shortUrl in a new Browser Session (so not yet logged into opendistro)
`{"statusCode":401,"error":"Unauthorized","message":"Authentication required"}`

it seems the redirect is missing. @zengyan-amazon ist that also fixed by the MR mentioned here?

**Comment by zengyan-amazon** [comment]
> we are on 1.10.1 and face some similar error, when using the shortUrl in a new Browser Session (so not yet logged into opendistro)
> `{"statusCode":401,"error":"Unauthorized","message":"Authentication required"}`
> 
> it seems the redirect is missing. @zengyan-amazon is that also fixed by the MR mentioned here?

yes, it is fixed in the PR above
