### ISSUE TITLE
Enable access to to be restricted to individual dashboards/visualisations

### ISSUE THREAD

**Issue by pbuxtonccuk** [opendistro-for-elasticsearch/security-kibana-plugin#6]
I'd like to be able to define user X, to have readonly access to specific dashboards.

I'd also like to give user X  readonly access to only specific visualisations.   If that visualisation is used in a dashboard they DO have access to, then  that visualisation should be available.

**Comment by shivdoshi** [comment]
@pbuxtonccuk You can use the multi-tenancy feature for this use-case. It has been enabled by-default in RPM and Docker distribution.

Basically, for each role, you can specify a tenant along with the access type (Read/Write or Read).  Then, all the dashboards created in that tenant stay in that tenant. Tenants can be changed from the right-side menu bar.

<img width="1001" alt="Screen Shot 2019-04-11 at 4 39 31 PM" src="https://user-images.githubusercontent.com/7130462/56002774-7cbb6e80-5c78-11e9-8776-2d58e53f9649.png">

We are working on adding documentation for this issue.

**Comment by shivdoshi** [comment]
Resolving, please re-open if you have additional queries.
