### ISSUE TITLE
Apps don't load when readonly_mode.roles set (ODFE 1.11.0)

### ISSUE THREAD

**Issue by js-timbirkett** [opendistro-for-elasticsearch/security-kibana-plugin#635]
Hey 👋 

I'm using OFE 1.11.0 (on K8S with Helm) with an anonymous user with auth like:
```json
{
  "username": "opendistro_security_anonymous",
  "tenants": {
    "global_tenant": true,
    "opendistro_security_anonymous": true
  },
  "roles": [
    "kibana_read_only",
    "kibana_user",
    "own_index",
    "read_only_logs"
  ],
  "backendroles": [
    "opendistro_security_anonymous_backendrole"
  ]
}
```
as you can see, the anonymous user is mapped to the `kibana_read_only` role which _should_ (or at least I think it should) prevent the user from creating things (visualizations, searches etc.) in the UI by default (https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/main/public/plugin.ts#L66)

This doesn't seem to work; the user can still create objects through the UI. So, I thought I'd try setting it up explicitly in `kibana.yml` with:

```yaml
opendistro_security.readonly_mode.roles:
  - kibana_read_only
```

The result is that nothing loads in Kibana UI, everything (including the login app) gives:
<img width="652" alt="Application Not Found Error" src="https://user-images.githubusercontent.com/57101177/100598453-a403fb00-32f6-11eb-9360-dda3b80f0a2d.png">

There is nothing in the Kibana logs, no errors in the JS console or Chrome Dev Tools. The user can access things like `/api/v1/restapiinfo` without issue.

Removing the above config and re-deploying the containers makes everything available again but also allows me to create and save Kibana objects even though I'm mapped to the `kibana_read_only` role. This feels like a 🦋 somewhere, but I'm not sure where (at the moment).

**Comment by yuxitang-amzn** [comment]
Hi js-timbirkett,

I believe it is fixed in this commit:
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/commit/dec85706fa38e00a88f9b3292f452e97b2b071e7

We don't have a patch release for this fix. You can build from source or wait for 1.12 release.

**Comment by yuxitang-amzn** [comment]
Duplicate of https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/562

**Comment by yuxitang-amzn** [comment]
I'm closing the issue. Feel free to comment or re-open if you have further concern.
