### ISSUE TITLE
Multi-tenancy: enforce quotas on tenants

### ISSUE THREAD

**Issue by spapadop** [opendistro-for-elasticsearch/security-kibana-plugin#637]
Being in a multi-tenant cluster, it would be interesting to be able to enforce some quotas on the different tenants.

For example if one tenancy goes beyond certain thresholds (either it is % or absolute) let's say in data size used, a relevant exception occurs so that it does not allow it. This would prevent certain tenants from abusing the cluster, affecting the rest peaceful ones. Also, it would allow better management of the cluster by the administrators.

**Comment by yuxitang-amzn** [comment]
@spapadop Hi,
Could you please provide the version you are testing?

And from my understanding you want some chars like `%` to be prohibited in tenant name, correct?

**Comment by spapadop** [comment]
Hello @yuxitang-amzn ,

I am testing with the current latest version 1.11.0 but I am not reported a bug, rather than an idea for enhancement.

I do not think that's relevant with the enhancement I am proposing:
> And from my understanding you want some chars like % to be prohibited in tenant name, correct?

As administrator of a cluster shared by multiple tenants (e.g. flights, logs), I want to be able to enforce for example the amount of data flights tenants can store, or the amount of processing power they can use.

To the best of my knowledge, that's not something currently available. Let me know if anything remains unclear.

**Comment by yuxitang-amzn** [comment]
I think I got some idea of your question. So you want to restrict the data size of some tenants?

I'm not sure if there is any misunderstanding of tenant, the data indices flights or logs are not tenant. The tenant saves only dashboards, visualizations and other kibana configs. From my understanding the tenant indices are more like metadata which are much smaller than data indices.

**Comment by yuxitang-amzn** [comment]
For the security plugin we manage the permission like read/write for indices/docs/fields. If you are looking for avoiding indices starts with small data but incrementally growing too large as time goes by, you may separate them by date and have a look at index management plugin to auto remove the oldest.

And for restricting the process power it is more like an Quality of Service topic which is in scope of this plugin.

**Comment by spapadop** [comment]
Thanks for your explanations. I get a better picture now.

So, let's say I have a **flights team** with indices: 
- flights-data-2020-11-01
- flights-data-2020-11-02
- flights-data-2020-11-03
...

and a **logs team** with indices:
- logs-data-2020-11-01
- logs-data-2020-11-02
- logs-data-2020-11-03
...

Given that their shared cluster has 100TB space, I want that the total of flights indices (flights-data-*) size to never surpass 50TB and same limit goes for the total logs indices (logs-data-*) size. Of course I could use the index management plugin to purge old data, but now we are talking about the hot -active- data.

Same concept for processing power. I don't want the flights team to run heavy queries that will take 90% of processing power at any given time, only letting logs team use 10% of processing power to straggle with their queries at any given time.

In  my head these are multi-tenancy problems that's why I placed the issue here, but if you think it belongs to a different plugin or forum please link me to it if possible, thanks a lot in advance.

**Comment by yuxitang-amzn** [comment]
https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/
Tenant is for grouping and sharing Kibana objects like visualization and dashboards. It doesn't manage data indices.

I don't have idea of any plugin providing QoS feature in opendistro.

I'll close this issue since the feature is out of scope. Feel free to re-open if you have further concern.
