### ISSUE TITLE
Kibana version input required while building from source

### ISSUE THREAD

**Issue by enp** [opendistro-for-elasticsearch/security-kibana-plugin#645]
I'm trying to build kibana 7.10.0 from source. I see 7.9.1 support in https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/main/package.json but also I see 7.10.0 in the same file tagged for v1.12.0.0, so I trying to use it (with yarn build as described in https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/627):

```
$ wget https://github.com/elastic/kibana/archive/v7.10.0.tar.gz
$ tar -xf v7.10.0.tar.gz 
$ cd kibana-7.10.0/
$ wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
$ . $HOME/.nvm/nvm.sh
$ nvm install $(cat .nvmrc)
$ nvm use
$ npm install -g yarn
$ cd plugins/
$ git clone --depth 1 --branch v1.12.0.0 https://github.com/opendistro-for-elasticsearch/security-kibana-plugin.git opendistro_security
$ cd opendistro_security/
$ yarn kbn bootstrap
$ yarn build
```

Last command result:

```
yarn run v1.22.10
$ yarn plugin-helpers build
$ node ../../scripts/plugin_helpers build
 warn DEPRECATED: rename [buildSourcePatterns] to [serverSourcePatterns] in [/home/enp/ci/bigtop/kibana-7.10.0/plugins/opendistro_security/.kibana-plugin-helpers.json]
 info Loaded config file from [/home/enp/ci/bigtop/kibana-7.10.0/plugins/opendistro_security/.kibana-plugin-helpers.json]
? What version of Kibana are you building for? 
```

But I see kibana version here:

```
$ head -8 package.json 
{
  "name": "opendistro_security",
  "version": "1.12.0.0",
  "main": "target/plugins/opendistro_security",
  "kibana": {
    "version": "7.10.0",
    "templateVersion": "1.0.0"
  },
```

Is this a bug or I'm doing something wrong?

**Comment by yuxitang-amzn** [comment]
Hi @enp ,

I'm not sure about your question. The build command will ask you "What version of Kibana are you building for?". Answer with 7.10.0 should be fine.

To be clear, main branch is still v1.11 for Kibana 7.9.1, and v1.12.0.0 is for Kibana 7.10.0. We are going to merge 1.12 into main after 1.12 release.
