### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/@elastic%2fsafer-lodash-set: Not found"

### ISSUE THREAD

**Issue by abhijithb92** [opendistro-for-elasticsearch/security-kibana-plugin#646]
I was building the security plugin(branch - opendistro-1.11) from within Kibana 7.9.1 when I got this error. I had run node plugins/security-kibana-plugin/build_tools/build_plugin.js from root directory of kibana. Same result when run from within security-kibana-plugin directory.

```
  stdout:
   'yarn install v1.22.10\ninfo No lockfile found.\n[1/5] Validating package.json...\n[2/5] Resolving packages...\ninfo If you think this is a bug, please open a bug report with the information provided in "/home/abhijith/kibana/kibana/build/kibana/kibana/yarn-error.log".\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.',
  stderr:
   'warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\nwarning request > har-validator@5.1.5: this library is no longer supported\nwarning @elastic/eui > highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest\nwarning @elastic/good > joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nwarning @elastic/good > oppsy@2.0.1: This module has moved and is now available at @hapi/oppsy. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.\nwarning @elastic/good > hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nwarning @elastic/good > joi > hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nwarning @elastic/good > oppsy > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.\nwarning @elastic/good > joi > topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.\nwarning @elastic/good > joi > topo > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.\nerror An unexpected error occurred: "https://registry.yarnpkg.com/@elastic%2fsafer-lodash-set: Not found".',
```

**Comment by yuxitang-amzn** [comment]
The "opendistro-1.11" branch is out of maintenance, could you try "main" branch which is still 1.11 now?

**Comment by abhijithb92** [comment]
@yuxitang-amzn I tried the main branch first. Got the same error. It was then that I decided to use this branch.

Here are the steps I followed to build.
1. Cloned kibana repo from elastic - https://github.com/elastic/kibana.git.
2. Checked out tag: v7.9.1
3. Created a directory plugins.
4. Inside the plugins directory, I cloned this repo.
5. From the root of kibana, I ran yarn kbn bootstrap.
6. Then I ran the build script.

**Comment by yuxitang-amzn** [comment]
@abhijithb92 As per [build guide](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin#build) we should run `node build_tools/build_plugin.js` from plugin folder, not kibana root. And the folder should be rename to opendistro_security, not security-kibana-plugin. Could you have a try?

**Comment by abhijithb92** [comment]
Building plugin...
CWD: /home/abhijith/kibana/kibana/plugins/opendistro_security
Cleaning up target directory...
Transpiling typescript soruces...
{ Error: Command failed with exit code 2: yarn tsc
error Command failed with exit code 2.
yarn run v1.22.10
$ /home/abhijith/kibana/kibana/plugins/opendistro_security/node_modules/.bin/tsc
../../src/core/server/http/router/request.ts(170,5): error TS2578: Unused '@ts-expect-error' directive.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at makeError (/home/abhijith/kibana/kibana/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/home/abhijith/kibana/kibana/node_modules/execa/index.js:188:17)
    at build (/home/abhijith/kibana/kibana/plugins/opendistro_security/build_tools/build_plugin.js:46:33)
    at /home/abhijith/kibana/kibana/plugins/opendistro_security/build_tools/build_plugin.js:161:11
    at Object.<anonymous> (/home/abhijith/kibana/kibana/plugins/opendistro_security/build_tools/build_plugin.js:165:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  shortMessage: 'Command failed with exit code 2: yarn tsc',
  command: 'yarn tsc',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout:
   'yarn run v1.22.10\n$ /home/abhijith/kibana/kibana/plugins/opendistro_security/node_modules/.bin/tsc\n../../src/core/server/http/router/request.ts(170,5): error TS2578: Unused \'@ts-expect-error\' directive.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.',
  stderr: 'error Command failed with exit code 2.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
```

**Comment by yuxitang-amzn** [comment]
@abhijithb92 
Please do a hack this step from kibana root folder and try again
`sed -i '170d' src/core/server/http/router/request.ts`

This is an temp solution in 1.11 because we disable some lint errors since the current plugin code is not in perfect style.

**Comment by abhijithb92** [comment]
@yuxitang-amzn  
Thanks a lot for the solution. The plugin got built successfully. Let me close the issue.
