### ISSUE TITLE
Application Not Found when logged with non admin user (Part 2)

### ISSUE THREAD

**Issue by gferrette** [opendistro-for-elasticsearch/security-kibana-plugin#651]
Hello,

I've installed Opendistro version 1.12 and the same problem as the issue #643 still persists as described below:

When i try to loggin with a non admin user, for example, an internal user the login page is redirect to the error below:

![image](https://user-images.githubusercontent.com/44647577/102481575-a8434e80-4040-11eb-91a4-b2c43b04ef18.png)

The user that i'm testing is the teste_user and has the permissions as below:

![image](https://user-images.githubusercontent.com/44647577/102481923-33bcdf80-4041-11eb-8869-8f631ddfc168.png)

When i try to login with teste_user and i select ,for example, global tenant or any other, is redirect to the page http://hostname:5601/app/opendistro_security and the error "Application Not Found" shows up.
If i change the address http://hostname:5601/app/opendistro_security to http://hostname:5601/app/home, the login succeds as the image below:

![image](https://user-images.githubusercontent.com/44647577/102482401-e2612000-4041-11eb-998c-e1e995ef988c.png)

It seems that when i try to login the application tries to open the "app/opendistro_security" and the internal user don't has admin rights.

Is there any configuration that i am missing?

Thanks in advance!

Gabriel.

**Comment by yuxitang-amzn** [comment]
Hi gferrette,

> It seems that when i try to login the application tries to open the "app/opendistro_security" and the internal user don't has admin rights.
You are right. It happens after you log out with an admin. 

When log out we will keep the original url in `nextUrl` parameter, this is basically to allow user to continue they work after session time out and logging again. I guess you logged in with admin, logged out on a security plugin page and then log in with a non-admin. In this case it will be redirected to security plugin page which is not accessible to non-admin.

You can just remove the `nextUrl` parameter if you want to log in with non-admin after log out with admin. Or what I usually do is have 2 windows, one window with admin and an incognito window with non-admin to test permission.

**Comment by gferrette** [comment]
Hello @yuxitang-amzn !

Yes, you are right! I was logging in first with an admin account and after that with a non admin user. If i close the window and start Kibana in a new one with a internal user, the error was not occuring.

Thanks a lot!
