### ISSUE TITLE
Application Not Found when the admin user opens the security interface and login out，use a sub user to login

### ISSUE THREAD

**Issue by bigfishman** [opendistro-for-elasticsearch/security-kibana-plugin#658]
es version 7.9.3   opendistro·_security  1.11.0.0

1、admin user login

2、 opens the security interface 
      
      chlick security management：

```
      the url is : https://ip:5601/app/opendistro_security#/app/opendistro_security/getstarted
```
3、 admin login out

```
     the  url is : https://ip:5601/app/login?nextUrl=%2Fapp%2Fopendistro_security
```
4、use a sub user to log in

```
  first url : https://ip:5601/app/select_tenant?nextUrl=%2Fapp%2Fopendistro_security
``` 
 then  you need chose a tenant, click confirm
```
  url  change to: https://ip:port/app/opendistro_security
```
 The sub-user does not have access to the security interface， it show  Application Not Found

**Comment by yuxitang-amzn** [comment]
Dup of https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/651
