### ISSUE TITLE
how can i add kibana read only user only has dashboard +  discovery + visualize + workbench page rights

### ISSUE THREAD

**Issue by ly123-liu** [opendistro-for-elasticsearch/security-kibana-plugin#670]
it seem that only all_access role mapper to user, user can see all those page(discovery，visualize, workbench, dev tools), when i change someuser only has the kibana-read-only role, they can only see dashbord page, but this is not enough

since all_access role has so many navigator list , such as management , enterprise search ... ， i just want those read-only user has some special page, such as dashboard, discovery, visualize, workbench , 

how can i add kibana read only user discovery and visualize and workbench page ? 

thans！

**Comment by yuxitang-amzn** [comment]
Hi @ly123-liu ,

We don't have this kind of role.

You may try a granting `read` in cluster permission, and granting `read` on indices. This will still show all nav buttons including management, but have no permission to update.
