### ISSUE TITLE
full mulltitenancy support?

### ISSUE THREAD

**Issue by hermanhmlee** [opendistro-for-elasticsearch/security-kibana-plugin#7]
Does OpenDistro support multitenancy? 

I see this in my config.yml:
`# Kibana multitenancy -`
`# see <TBD>`
`# To make this work you need to install <TBD>`

**Comment by hardik-k-shah** [comment]
Yes, OpenDistro supports multi-tenancy by default. You do not need any specific configuration to enable Multi-tenancy.

**Comment by hermanhmlee** [comment]
ok great, I got it working too and things seem to work fine. Thanks for the confirmation.
