### ISSUE TITLE
Security Config visible for users that don't have access to it

### ISSUE THREAD

**Issue by tremmert** [opendistro-for-elasticsearch/security-kibana-plugin#86]
When I log into Opendistro Kibana, with the standard kibanaro user, or another self-created user that has no access to security config, the security icon is still visible, and when clicked on, the security config screen is partially renderred (just the authentication and authorization icon)

![Screenshot 2019-09-08 at 21 41 11](https://user-images.githubusercontent.com/1215797/64494490-7233ee00-d285-11e9-813f-7f3477b7d31b.png)

When you click on the remaining icon, it doesn't actually let you view anything, but redirects to the login page...

Shouldn't this be hidden completely for users that don't have access. 

It confuses users, and doesn't look very nice when you do get in it.

I **think** in the past when I played with SearchGuard, the security config wasn't visible at all if one didn't have access to it?

(This happens with any version of opendistro from 0.8.0 to 1.1.0)

**Comment by tremmert** [comment]
Ok, i have fixed that myself locally now for what I need.... doing 2 things: is there any interest in me putting this into fork and raising a pull request?

Here is what I have done locally:

1)

change to /public/apps/configuration/configuration.html

`<a id="opendistro_security.link.securityconfig" ng-if="endpointAndMethodEnabled('SECURITYCONFIG', 'GET')" class="FeaturePanel ng-scope"`

to make this 'CONFIG' cause SECURITYCONFIG does not exist as an endpoint, it CONFIG

this will remove the remaining one icon

2)

disable the security app and it showing up in the sidebar completey if the user does not have access rights to the security rest API (which is used by the security config).

change to public/chrome/configuration/enable_configuration.js

`    systemstate.loadRestInfo().then(function(){

        if(systemstate.getRestApiInfo().has_api_access === true) {

            chrome.getNavLinkById("security-configuration").hidden = false;
            FeatureCatalogueRegistryProvider.register(() => {
                return {
                    id: 'security-configuration',
                    title: 'Security Configuration',
                    description: 'Configure users, roles and permissions for Open Distro Security.',
                    icon: 'securityApp',
                    path: '/app/security-configuration',
                    showOnHomePage: true,
                    category: FeatureCatalogueCategory.ADMIN
                };
            });
        } else {
            return;
        }
    });`

**Comment by chuanzgh** [comment]
I haven't check the code on how everything links up, but for point 1, I think "SECURITYCONFIG" is supposed to be the correct naming. A recent commit: https://github.com/opendistro-for-elasticsearch/security-advanced-modules/commit/ca0e84b8816a09fb5c9e52ca7c1a01a77e9fe176

**Comment by tremmert** [comment]
Thank you @chuanzgh. Seems like https://github.com/opendistro-for-elasticsearch/security-advanced-modules/commit/ca0e84b8816a09fb5c9e52ca7c1a01a77e9fe176 is indeed fixing my point 1.

About point 2 I suggest I close this and open a separate issue? 

I think it would make sense to disable & hide the security configuration if a user does not have the access to the restAPI, as denoted by  `getRestApiInfo().has_api_access === true`
