### ISSUE TITLE
Using security-kibana-plugin with Elastic builds

### ISSUE THREAD

**Issue by monolithed** [opendistro-for-elasticsearch/security-kibana-plugin#89]
Is it possible to use the security-kibana-plugin with Elastic builds?

**Comment by bgagnon** [comment]
Not legally, if I understand the terms of section 2.1 of the Elastic License correctly: https://github.com/elastic/kibana/blob/master/licenses/ELASTIC-LICENSE.txt

Disclaimer: I am not a lawyer.

**Comment by sujithvm** [comment]
@monolithed Yes. You can use security-kibana-plugin with OSS elastic builds. 
This plugin is dependent on security plugin https://github.com/opendistro-for-elasticsearch/security so please make sure you install that as well. 

Please follow https://opendistro.github.io/for-elasticsearch-docs/docs/install/ for more documentation
